name: Auto Commit

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make a change
        run: |
          echo "Commit at $(date)" >> auto_commit.txt
          git config --global user.name 'Rafael Avella'
          git config --global user.email 'davraops@gmail.com'
          git add auto_commit.txt
          git commit -m "Automated commit"
      
      - name: Push changes
        run: |
          git push
